from itertools import chain
from os.path import basename

from pyeda.boolalg.bdd import bddvar

from rvhyno.codegen.utils import dump_codegen_position
from rvhyno.hnl.codegen.bdd import BDDNode, ConstBDDNode
from rvhyno.hnl.formula import Comparison, And, Or, Not, TrivialTrue, HLTLFormula
from ..shared import CodeGenCpp as CodeGenCppShared


class CodeGenCppAtoms(CodeGenCppShared):
    """
    Class for generating monitors in C++.

    See the parent classes for parameters' description.

    :param fixed_quantifiers:  assignment to quantifiers that stay fixed (do not change) in the monitor
                               generated by this codegen. That is, if `t1` is fixed in this monitor,
                               then it will refer to the same trace all the lifespan of the monitor
                               (while other quantifiers will get assigned different traces from the
                               trace sets).
    """

    def __init__(
        self,
        name,
        args,
        fixed_quantifiers=None,
        out_dir: str = None,
        namespace: str = None,
        embedded: bool = False,
    ):
        super().__init__(name, args, fixed_quantifiers, out_dir, namespace, embedded)

        self.BDD = None
        self._bdd_nodes = []
        self._bdd_vars_to_nodes = {}
        self._automata = {}
        self._atoms_files = []

    def generate_cmake(self, overwrite_keys=None):
        """
        `embedded` is True if the HNL monitor is a subdirectory in some other project
        """
        from config import vamos_buffers_DIR

        build_type = self.args.build_type
        if not build_type:
            build_type = '"Debug"' if self.args.debug else "Release"

        values = {
            # "vamos-buffers_DIR": vamos_buffers_DIR,
            "cg": self,
            "additional_sources": " ".join(
                (
                    basename(f)
                    for f in self.args.cpp_files
                    + self.args.add_gen_files
                    + self._add_gen_files
                )
            ),
            "atoms_sources": " ".join((basename(f) for f in self._atoms_files)),
            "additional_cflags": " ".join((d for d in self.args.cflags)),
            "CMAKE_BUILD_TYPE": build_type,
            "monitor_name": self.name(),
            "add_submonitors": "\n".join(
                (
                    f"add_subdirectory({submon_dir})"
                    for submon_dir in (d["out_dir"] for d in self._submonitors)
                )
            ),
            "submonitors_libs": " ".join(self._submonitors),
        }
        if overwrite_keys:
            values.update(overwrite_keys)

        if self._embedded:
            cmakelists = "atoms/CMakeLists-embedded.txt.in"
        else:
            cmakelists = "atoms/CMakeLists.txt.in"
        self.gen_file(cmakelists, "CMakeLists.txt", values)

    def _gen_bdd_from_formula(self, formula):
        """
        Generate BDD from the formula that will give us the order of evaluation
        of atoms
        """

        def gen_bdd(F):
            """
            Recursively build BDD from the formula and create the mapping
            between atoms and BDD variables. Each atom represents a variable.
            """
            if isinstance(F, (Comparison, HLTLFormula)):
                v = bddvar(str(F))
                if isinstance(F, TrivialTrue):
                    # turn the BDD node into TRUE
                    v = v | ~v
                else:
                    nd = BDDNode(F, v)
                    self._bdd_nodes.append(nd)
                    self._bdd_vars_to_nodes[v] = nd
                return v
            if isinstance(F, And):
                return gen_bdd(F.children[0]) & gen_bdd(F.children[1])
            if isinstance(F, Or):
                return gen_bdd(F.children[0]) | gen_bdd(F.children[1])
            if isinstance(F, Not):
                return ~gen_bdd(F.children[0])
            raise NotImplementedError(f"Not implemented operation: {F}")

        BDD = gen_bdd(formula.formula)
        if self.args.debug:
            with self.new_dbg_file("BDD.dot") as f:
                f.write(BDD.to_dot())

        if BDD.is_one() or BDD.is_zero():
            assert not self._bdd_nodes, self._bdd_nodes
            # we have constructed no BDD nodes, because we have only the trivial BDD true/false.
            # But even for true/false, we need to build the atom (a special one).
            # Add this special BDDNode
            self._bdd_nodes.append(ConstBDDNode(formula.formula, BDD))

        self.BDD = BDD

    def _generate_bdd_code(self, formula):
        self.gen_file("formula-state.h.in", "formula-state.h", {"cg": self})

    def get_formula_bdd_actions(self):

        def bdd_to_action(bdd):
            if bdd.is_one():
                return "RESULT_TRUE"
            elif bdd.is_zero():
                return "RESULT_FALSE"

            nd = self._bdd_vars_to_nodes[bdd.top]
            return f"ATOM_{nd.get_id()}"

        # this is so stupid, but I just cannot get the variable
        # for the node, because PyEDA does not have getters for `_VARS`
        # dictionary. So I'm just generating sub-BDDs from which I
        # can get the root variable.
        rows = {}
        if self.BDD.is_zero() or self.BDD.is_one():
            rows[1] = {}
            rows[1][True] = "RESULT_TRUE"
            rows[1][False] = "RESULT_FALSE"
            return rows

        seen, wbg = set(), set()
        wbg.add(self.BDD)
        while wbg:
            bdd = wbg.pop()
            if bdd in seen:
                continue
            seen.add(bdd)

            hi = bdd.restrict({bdd: 1})
            lo = bdd.restrict({bdd: 0})
            wbg.add(hi)
            wbg.add(lo)

            if bdd.top:
                nd = self._bdd_vars_to_nodes[bdd.top]
                assert nd.get_id() not in rows, rows
                atom_id = nd.get_id()

                rows[atom_id] = {}
                rows[atom_id][True] = bdd_to_action(hi)
                rows[atom_id][False] = bdd_to_action(lo)
            elif bdd.is_zero():
                pass
        return rows

    def get_initial_atom(self) -> str:
        # FIXME: TRUE and FALSE BDDs still may break this code,
        # we need to handle them on some higher level (ideally just do not create this instance
        # and immediately solve it)
        BDD = self.BDD
        if BDD.top:
            nd_id = self._bdd_vars_to_nodes[BDD.top].get_id()
        else:
            assert BDD.is_one() or BDD.is_zero(), BDD
            nd_id = 1
        return f"ATOM_{nd_id}"

    def _create_instance(self, formula, wr):
        dump_codegen_position(wr)
        args = ",".join(
            chain(
                (str(q.var) for q in formula.quantifier_prefix),
                (f"/* fixed */ {q.var}" for q in self._fixed_quantifiers or ()),
            )
        )
        print_args = '<< ", " <<'.join(
            (f"{q.var}->id()" for q in formula.quantifier_prefix)
        )
        wr(
            f"""
           auto *instance = new Instance{{{args}, INITIAL_ATOM}};
           ++stats.num_instances;

           instance->monitor = createAtomMonitor(INITIAL_ATOM, *instance);

           #ifdef DEBUG_PRINTS
           std::cerr << "Instance[init, " << {print_args} << "]\\n";
           #endif /* !DEBUG_PRINTS */
        """
        )

    def _gen_create_instance_reduced(self, formula, wr):
        dump_codegen_position(wr)
        if len(formula.quantifier_prefix) > 2:
            raise NotImplementedError(
                "Reductions work now only with at most 2 quantifiers"
            )

        # if "symmetric" in self.args.reduction:
        dump_codegen_position(wr)
        wr(
            """
            auto *t1 = t_new;
            for (auto &[t2_id, t2_ptr] : traces) {
                auto *t2 = t2_ptr;
        """
        )
        if "reflexivity" in self.args.reduction:
            dump_codegen_position(wr)
            wr(
                """
            if (t1 == t2) {
                continue;
            }
            """
            )

        dump_codegen_position(wr)
        wr(
            """
            auto *instance = new Instance{t1, t2, INITIAL_ATOM};
            ++stats.num_instances;

            instance->monitor = createAtomMonitor(INITIAL_ATOM, *instance);

        #ifdef DEBUG_PRINTS
             std::cerr << "Instance[init, " << t1->id() << ", " << t2->id() << "]\\n";
        #endif /* !DEBUG_PRINTS */
        """
        )

        dump_codegen_position(wr)
        if not "symmetry" in self.args.reduction:
            wr(
                """
                instance = new Instance{t2, t1, INITIAL_ATOM};
                ++stats.num_instances;

                instance->monitor = createAtomMonitor(INITIAL_ATOM, *instance);

            #ifdef DEBUG_PRINTS
                std::cerr << "Instance[init, " << t2->id() << ", " << t1->id() << "]\\n";
            #endif /* !DEBUG_PRINTS */
            """
            )
        wr("}\n")

    def _generate_hnlinstances(self, formula):

        def trace_variables(nd):
            return [t.name for t in nd.formula.trace_variables()]

        self.gen_file(
            "atoms/instance.h.in",
            "instance.h",
            {"cg": self, "formula": formula, "trace_variables": trace_variables},
        )
