"""
Code generation for hypernode logic -- the top-level codegen class.
"""

from typing import Tuple
from itertools import chain
from os import readlink, makedirs
from os.path import abspath, dirname, islink, join as pathjoin, basename

from rvhyno.codegen.codegencpp import CodeGenCpp
from rvhyno.codegen.utils import dump_codegen_position
from rvhyno.hnl.codegen.submonitors.atoms import get_atoms_codegen
from rvhyno.hnl.codegen.submonitors.submon import CodeGenCpp as CodeGenCppSubMon
from rvhyno.hnl.codegen.utils import c_type_bounds
from rvhyno.hnl.formula import (
    Constant,
    Function,
    PrenexFormula,
)

from rvhyno.utils import log_indent_incr, log_indent_decr, msg


def _check_functions(functions) -> None:
    """Check if the generator functions are used consistently in the formula

    :param functions:     A container with functions taken from the formula.
    :raises RuntimeError: If an inconsistency is detected.
    """

    funs = {}
    for fun in functions:
        f = funs.get(fun.name)
        if f is None:
            funs[fun.name] = fun
        else:
            if len(f.traces) != len(fun.traces):
                raise RuntimeError(
                    f"Function '{fun.name}' is used multiple time with different number of arguments:\n{fun} and {f}"
                )


def _get_num_range(data: list) -> Tuple[int, int]:
    """Get the minimum and maximum number that can be stored in the data fields of events.

    In other words, find if there are some bounds on the alphabet or if the alphabet
    are arbitrary numbers of the given data types.
    (The description of data fields is passed using the `--data` option to the main script).
    """
    min_n, max_n = None, None
    for name, ty in data:
        rng = ty[1]
        if rng is None:
            return None
        if min_n is None or rng[0] < min_n:
            min_n = rng[0]
        if max_n is None or rng[1] > max_n:
            max_n = rng[1]

    return min_n, max_n


def _check_formula(formula, args):
    field_names = set((x[0] for x in args.data))
    for t in formula.program_variables():
        if t.name not in field_names and t.name not in args.data_fun:
            raise RuntimeError(
                f"Formula is using data '{t.name}' which I don't know. I know: {field_names} and data functions: {args.data_fun}"
            )


def _has_finite_alphabet(alphabet, args) -> bool:
    """Check if we have a finite alphabet"""
    return (
        bool(alphabet) or bool(args.alphabet) or _get_num_range(args.data) is not None
    )


class CodeGenCppTopLevel(CodeGenCpp):
    """
    Class for generating eHL/sHL monitors in C++.
    The main function to be called is :meth:`generate`.

    The generated monitor consists of a top-level monitor which is just a wrapper
    for the actual monitor. More precisely, this wrapper encapsulates the actual monitor
    and the set of traces that it processes.

    The actual monitor itself can have sub-monitors (depending on the structure of the formula).
    There is one sub-monitor class generated for each quantifier alternation in the formula
    (or a different set of traces quantified).
    The final monitors that process the traces are _atom_ monitors -- these literally implement
    a run of an automaton on the given traces.
    For example, consider formula `forall t1. exists t2. forall t3. φ(t1, t2, t3)`.
    The generated project will have the following structure:
    ```
    - top-level-monitor (wrapping submonitor-1 and the input traces)
      - submonitor-1      # instantiates t1
        - submonitor-2    # instantiates t2
          - atom monitor  # instantiates t3 and evaluates φ on t1, t2, t3
    ```

    If there are generator functions used, their traces are stored and managed (added, extended)
    by the top-level monitor.

    In summary, this is the top-level `CodeGenCpp` that takes care of creating `main.cpp` and files
    shared by all the (sub-)monitors, like `events.h`, `csvreader.h`, and
    files related to generator functions (if applicable).
    Sub-monitors that do actually do some work with the traces are generated by other codegens that are used from
    this class.
    """

    def __init__(
        self,
        args,
        out_dir: str = None,
        namespace: str = None,
        name="monitor",
        embedded=False,
    ):
        super().__init__(args, out_dir, namespace, name, embedded)

        self_dir = abspath(
            dirname(readlink(__file__) if islink(__file__) else __file__)
        )
        self.templates_path = pathjoin(self_dir, "templates/")
        self._has_generator_functions = None

    def has_generator_functions(self) -> bool:
        """
        :return: `True` if the formula to be monitored (by the top-level monitor)
                  uses generator functions.
        :raises RuntimeError:  if this function is called before the answer is known
        """
        if self._has_generator_functions is None:
            raise RuntimeError("Not set yet!")

        return self._has_generator_functions

    def copy_files(self):
        # copy files from the CMD line
        for f in self.args.cpp_files:
            self.copy_file(f)

        # copy common templates
        files = [
            "monitor.h",
            "monitor-with-traces.h",
            "cmd.h",
            "cmd.cpp",
            "stream.h",
            "trace.h",
            "trace.cpp",
            "tracesetbase.h",
            "tracesetbase.cpp",
            "traceset.h",
            "traceset.cpp",
            "tracesetview.h",
            "tracesetview.cpp",
            "verdict.h",
        ]

        if self.has_generator_functions():
            files.extend(["sharedtraceset.h", "sharedtraceset.cpp", "function.h"])

        from_dir = self.common_templates_path
        for f in files:
            if f not in self.args.overwrite_file:
                self.copy_file(f, from_dir=from_dir)

    def generate_cmake(self, formula, overwrite_keys=None):
        """
        `embedded` is True if the HNL monitor is a subdirectory in some other project
        """
        # from config import vamos_buffers_DIR

        build_type = self.args.build_type
        if not build_type:
            build_type = '"Debug"' if self.args.debug else "Release"
            self.args.build_type = build_type

        values = {
            # "vamos-buffers_DIR": vamos_buffers_DIR,
            "cg": self,
            "formula": formula,
            "additional_sources": " ".join(
                (
                    basename(f)
                    for f in self.args.cpp_files
                    + self.args.add_gen_files
                    + self._add_gen_files
                )
            ),
            "additional_cflags": " ".join((d for d in self.args.cflags)),
            "CMAKE_BUILD_TYPE": build_type,
            "monitor_name": self.name(),
            "top_monitor_dir": self._out_dir,
            "submonitors_libs": " ".join((d["name"] for d in self._submonitors)),
            "submonitors": "\n".join(
                (f'add_subdirectory({d["out_dir_rel"]})' for d in self._submonitors)
            ),
        }
        if overwrite_keys:
            values.update(overwrite_keys)

        if self._embedded:
            cmakelists = "top/CMakeLists-embedded.txt.in"
        else:
            cmakelists = "top/CMakeLists.txt.in"
        self.gen_file(cmakelists, "CMakeLists.txt", values)
        self.gen_file("CMakeLists-options.txt.in", "CMakeLists-options.txt", values)
        self.gen_file("CMakeLists-common.txt.in", "CMakeLists-common.txt", values)

    def _generate_events(self):
        self.gen_file("events.h.in", "events.h", {"data": self.args.data})
        self.gen_file("events.cpp.in", "events.cpp", {"data": self.args.data})

        # FIXME: do this more programmer-friendly
        self._add_gen_files.append("events.cpp")

    def _generate_csv_reader(self):
        self.copy_file("csvreader.h", from_dir=self.common_templates_path)
        self.copy_file("csvreader.cpp", from_dir=self.common_templates_path)
        self._add_gen_files.append("csvreader.cpp")

        self.gen_file(
            "read_csv_event.h.in", "read_csv_event.h", {"data": self.args.data}
        )

    def _gen_function_files(self, fun: Function):
        with self.new_file(f"function-{fun.name}.h") as f:
            wr = f.write
            ns = self.namespace()
            wr(
                f"""
            #ifndef _FUNCTION_{fun.name}_H__{ns}
            #define _FUNCTION_{fun.name}_H__{ns}
            """
            )

            wr('#include "function.h"\n')
            wr('#include "sharedtraceset.h"\n\n')

            wr(f"class Function_{fun.name} : public Function{{\n")

            wr("public:\n")
            wr(" virtual SharedTraceSet& getTraceSet(")
            wr(", ".join((f"Trace *{tr.name}" for tr in fun.traces)))
            wr(") = 0;\n")
            wr("};\n")
            wr("#endif\n")

    def generate_functions(self, functions):
        with self.new_file("functions.h") as f:
            dump_codegen_position(f)
            wr = f.write
            wr(f"#ifndef HNL_FUNCTIONS__{self.name()}\n")
            wr(f"#define HNL_FUNCTIONS__{self.name()}\n")
            wr("#include <memory>\n")
            wr('#include "function.h"\n\n')
            for fun in functions:
                wr(f'#include "function-{fun.name}.h"\n')
            wr("\n\n")
            for fun in functions:
                wr(
                    f"std::unique_ptr<Function> createFunction_{fun.name}(CmdArgs *cmd);\n"
                )
            wr(f"#endif // !HNL_FUNCTIONS__{self.name()}\n")

        for fun in functions:
            self._gen_function_files(fun)

    def generate_alltracesets_class(self, functions):

        with self.new_file("alltracesets.h") as f:
            dump_codegen_position(f)
            wr = f.write
            wr(f"#ifndef HNL_ALLTRACESETS__{self.name()}\n")
            wr(f"#define HNL_ALLTRACESETS__{self.name()}\n\n")

            wr('#include "traceset.h"\n')

            for fun in functions:
                wr(f'#include "function-{fun.name}.h"\n')

            wr("\n")

            wr(self.namespace_start())

            wr(
                "\n\n/* An object passed to monitors with references to traces and functions */\n"
            )
            wr("struct AllTraceSets {\n")
            wr(" TraceSet& traces;")
            for fun in functions:
                wr(f"  Function_{fun.name}& {fun.name};\n")
            wr("\n")
            fun_args = ",".join(
                (f"Function_{fun.name}& {fun.name}" for fun in functions)
            )
            fun_init = ",".join((f"{fun.name}({fun.name})" for fun in functions))
            wr(
                f"  AllTraceSets(TraceSet& traces{', ' if fun_args else ''}{fun_args}) : traces(traces) {',' if fun_init else ''} {fun_init} {{}}\n"
            )

            wr("};\n\n")

            wr(self.namespace_end())

            wr(f"#endif // !HNL_ALLTRACESETS__{self.name()}\n")

    def gen_data_funs(self):
        if not self.args.data_fun:
            return

        from rvhyno.automata.transducers import transducer_from_yaml

        data_funs = {}
        for fn in self.args.data_fun:
            name, T = transducer_from_yaml(fn, self.args.data)
            data_funs[name] = T

            if self.args.debug:
                with self.new_dbg_file(f"aut-{name}.dot") as f:
                    T.to_dot(f)

        self.args.data_fun = data_funs

    def generate(self, formula: PrenexFormula, alphabet=None) -> None:
        """
        The top-level function to generate code

        :param formula:  the input formula in the *prenex form*
        :type formula:   :class:`PrenexFormula
        :param alphabet:  alphabet to use; optional for sHL, necessary for eHL monitors.
        """
        if not self._embedded:
            self.gen_data_funs()

        _check_formula(formula, self.args)

        if self.args.logic == "ehl":
            if not _has_finite_alphabet(alphabet, self.args):
                raise RuntimeError("No finite alphabet given, cannot use eHL logic.")

            self.args.alphabet = alphabet or self._get_alphabet()

        if not self._embedded:
            if self.args.gen_csv_reader:
                self._generate_csv_reader()

            self._generate_events()
            self.generate_main()

        functions_instances = formula.functions()
        functions = list(set(functions_instances))
        # check types of functions
        _check_functions(functions_instances)

        self._has_generator_functions = bool(functions)

        if self.has_generator_functions():
            self.generate_functions(functions)

        self.generate_alltracesets_class(functions)

        has_submonitors = formula.has_different_quantifiers()
        # Generate the actual monitors. If there is no quantifier alternation,
        # generate directly the monitor for the body of the formula.
        # Otherwise, generate a monitor that has sub-monitors for the sub-formulas
        # where the formula alternates.
        submon_name = self.sub_name()
        nested_out_dir_rel = "submonitor"
        nested_out_dir = f"{self._out_dir}/{nested_out_dir_rel}"
        nested_namespace = self.sub_namespace()
        self._submonitors = [
            {
                "name": submon_name,
                "out_dir": nested_out_dir,
                "out_dir_rel": nested_out_dir_rel,
                "namespace": nested_namespace,
            }
        ]

        if has_submonitors:
            codegen = CodeGenCppSubMon(
                submon_name,
                self.args,
                out_dir=nested_out_dir,
                namespace=nested_namespace,
                embedded=True,
            )
        else:
            codegen = get_atoms_codegen(formula, self.args.logic)(
                submon_name,
                self.args,
                out_dir=nested_out_dir,
                namespace=nested_namespace,
                embedded=True,
            )

        log_indent_incr()
        self.args.out_dir_overwrite = (
            False  # FIXME: do this more elegantly, this is more or less a hack
        )
        codegen.generate(formula)
        log_indent_decr()

        self.generate_monitor(formula)

        if not self._embedded:
            self.copy_files()

        if self.args.gen_experiments:
            self.generate_experiments()

        # cmake generation should go at the end so that
        # it knows all the generated files
        self.generate_cmake(formula)

        # Generate a README for the monitor
        self.gen_file(
            "top/README.md.in",
            "README.md",
            {
                "cg": self,
                "formula": formula,
                "cmd": [f"'{s}'" if " " in s else s for s in self.args.cmd],
            },
        )
        self.gen_file("top/HACKING.md.in", "HACKING.md", {"cg": self})

        if self.args.debug:
            with self.new_dbg_file(f"args.txt") as f:
                f.write("".join(f"{k} : {v}\n" for k, v in vars(self.args).items()))

        self.format_generated_code()

    def _get_alphabet(self):
        alphabet = self.args.alphabet
        if alphabet:
            alphabet = [Constant(a) for a in alphabet.split(",")]
        else:
            data = self.args.data
            num_range = _get_num_range(data)
            if num_range is None:
                raise RuntimeError(
                    "No explicit alphabet given and failed to get a bound on numbers from data"
                )
            alphabet = [Constant(str(a)) for a in range(num_range[0], num_range[1] + 1)]

        if not alphabet:
            raise RuntimeError("The alphabet is empty, eHL needs explicit alphabet.")
        return alphabet

    def _functions_mon_h_str(self, functions):
        init = ", ".join(
            (
                f"function_{fun.name}(createFunction_{fun.name}(_cmd))"
                for fun in functions
            )
        )
        init = f", {init}" if init else ""
        return (
            "\n".join(
                (f"std::unique_ptr<Function> function_{fun.name};" for fun in functions)
            ),
            init,
        )

    def _functions_mon_cpp_str(self, functions):
        step = "\n".join((f"function_{fun.name}->step();" for fun in functions))
        finished = [
            f"_inputs_finished &= function_{fun.name}->finished();" for fun in functions
        ]
        return step, "\n".join(finished)

    def generate_monitor(self, formula):
        functions_instances = formula.functions()
        functions = list(set(functions_instances))

        funs, funs_init = self._functions_mon_h_str(functions)
        funs_step, funs_finished = self._functions_mon_cpp_str(functions)
        alltracesets_init = ",".join(
            chain(
                ("_traces",),
                (
                    f"*static_cast<Function_{fun.name}*>(function_{fun.name}.get())"
                    for fun in functions
                ),
            )
        )

        values = {
            "monitor_name": self.name(),
            "namespace": self.namespace(),
            "namespace_start": self.namespace_start(),
            "namespace_end": self.namespace_end(),
            "functions": funs,
            "functions_init": funs_init,
            "functions_step": funs_step,
            "functions_finished": funs_finished,
            "alltracesets_init": alltracesets_init,
        }

        self.gen_file("top/formula-monitor.h.in", "formula-monitor.h", values)
        self.gen_file("top/formula-monitor.cpp.in", "formula-monitor.cpp", values)

    def _event_data_bounds(self, ty: str, min_b=None, max_b=None) -> Tuple[int, int]:
        """
        Compute the minumum and maximum value that can be stored in a given data filed of an event.
        This is based on its type, the required alphabet and bounds taken from `--data`.
        """
        vmin, vmax = c_type_bounds(ty)
        assert vmin is not None
        assert vmax is not None

        alphabet = self.args.alphabet
        if alphabet:
            if isinstance(alphabet, str) and alphabet.endswith("b"):
                bits = int(alphabet[:-1])
                vmin = max(0, vmin)
                vmax = min(2**bits - 1, vmax)
            else:
                raise NotImplementedError(f"This alphabet is unhandled: {alphabet}")

        assert vmin is not None
        assert vmax is not None
        if min_b is not None:
            if vmin < min_b:
                vmin = min_b
        if max_b is not None:
            if vmax > max_b:
                vmax = max_b

        return vmin, vmax

    def generate_experiments(self) -> None:
        """Generate a sample experiments setup.

        Generate a folder containing a set of random input traces
        (more precisely, we generate a script that generates the traces
        so that users can alter it to their needs),
        and scripts that run experiments over these (or any other) traces
        with the monitor.
        """
        msg("info", "Generating sample experiments", section=3)

        # generating tests for atoms is not implemented right now,
        # but we still create the sub-dir so that we can keep the current
        # cmake without changes
        makedirs(f"{self._out_dir}/experiments", exist_ok=True)
        makedirs(f"{self._out_dir}/experiments/random-traces", exist_ok=True)

        self.gen_file(
            "top/experiments/CMakeLists.txt.in",
            "experiments/CMakeLists.txt",
            {"cg": self},
        )
        self.gen_file(
            "top/experiments/generate_traces.py.in",
            "experiments/generate_traces.py",
            {"cg": self, "data_bounds": self._event_data_bounds},
            creation_header="py",
        )
        self.gen_file(
            "top/experiments/run.py",
            "experiments/run.py",
            {"cg": self},
            creation_header="py",
        )
        self.gen_file(
            "top/experiments/README.md.in", "experiments/README.md", {"cg": self}
        )

    def generate_main(self):
        self.gen_file(
            "main.cpp.in",
            "main.cpp",
            {
                "cg": self,
            },
        )
